# @package _global_

# Define key values here that are used multiple times in the config files.
config_schema_kind: examples.rotary_normal_embedding.schemas.RoNEConfigSchema
dataset_kind: examples.rotary_normal_embedding.datasets.caeml.dataset.DrivAerMLDataset
excluded_properties: 
  - volume_sdf
  - volume_normals
defaults:
  - data_specs: caeml
  - dataset_normalizers: caeml_dataset_normalizers
  - model: ??? # models are undefined and will be defined per experiment 
  - trainer: caeml_trainer
  - datasets: caeml_dataset
  - tracker: rone_encoding # trackers are undefined and will be defined depending on either development, training or evaluation
  - callbacks: training_callbacks_caeml
  - pipeline: caeml_pipeline
  - /pipeline@inference_pipeline: caeml_pipeline
  - dataset_statistics: drivaerml_stats
  - optimizer: adamw
  - _self_

stage_name: train
store_code_in_output: false
output_path: ./outputs
dataset_root: /nfs-gpu/research/datasets/drivaerml/preprocessed/subsampled_10x
